apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-prom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-prom
  template:
    metadata:
      labels:
        app: express-prom
    spec:
      containers:
      - name: express-prom
        image: junereycasuga/node-prom:1.0.0
        ports:
        - name: web
          containerPort: 3000
