apiVersion: v1
kind: Pod
metadata:
  name: express-pod
spec:
  containers:
    - name: express
      image: junereycasuga/node-prom:1.0.0
      ports:
        - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
