apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: express-prom
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: express-prom
  endpoints:
    - port: web
      path: /metrics
