apiVersion: v1
kind: Service
metadata:
  name: express-prom
  labels:
    app: express-prom
spec:
  type: NodePort
  selector:
    app: express-prom
  ports:
  - name: web
    port: 80
    targetPort: 3000
    nodePort: 30001
